### ISSUE TITLE
tests all show as failed in test explorer

### ISSUE THREAD

**Issue by wsheboy** [Lej/vscode-lua-test-adapter#1]
Using the provided example test code from the readme, all of the tests show as failed in test explorer in Visual Studio Code.  When run from terminal the tests work as expected.

**Comment by Lej** [comment]
Not enough information provided. Need to be reproducible for me to be able to do anything.

I have made a full working example (assuming `.vscode/settings.json` is correctly configured) available here [https://github.com/Lej/vscode-lua-test-adapter-example](https://github.com/Lej/vscode-lua-test-adapter-example). Closing.

**Comment by wsheboy** [comment]
To follow-up with more information, your example works when tests are not grouped within a table.  

When grouped in order to use setUp() and tearDown() as shown here https://luaunit.readthedocs.io/en/latest/ then the following error occurs:

C:/Program Files/Lua/lua54.exe: .\test/luaunit.lua:3312: No such name in global space: TestNameOfMyTest
stack traceback:
	[C]: in function 'error'
	.\test/luaunit.lua:3312: in method 'internalRunSuiteByNames'
	.\test/luaunit.lua:3414: in function <.\test/luaunit.lua:3411>
	(...tail calls...)

The same tests work correctly when called from a command window, so the issue does not appear to be in the luaunit code.
